config/routes.rb
Divvyup::Application.routes.draw do

  devise_for :groups
  resources :people
  
  resources :item_types
  
  resources :items do
    post :finish
  end
  
  resources :uses

  
  authenticated :group do
    root to: 'items#index', as: "authenticated_root"
  end

  unauthenticated do
    root to: 'welcome#index', as: "unauthenticated_root"
  end

end

app/models/person.rb
class Person < ActiveRecord::Base
  include SharedMethods

  # validations
  validates :group_id, presence: true
  validates :name, length: { minimum: 1 }

  # relations
  belongs_to :group
  has_many :uses
  has_many :items

  # scopes
  default_scope { order(name: :asc) }

  # get the amount used for a particular item
  def amount_of_item_used(item)
    used = 0.0
    unit = base_unit(item.item_type.measure_by)

    item.uses.each do |use|
      if use.person_id == id
        used += use.amount_used
      end
    end

    return [used, unit]
  end

  # same, but for item types
  def amount_of_item_type_used(item_type)
    total_used = 0.0
    unit = base_unit(item_type.measure_by)

    item_type.items.each do |item|
      used, unit = self.amount_of_item_used(item) # check how much has been used
      if used > 0 # if it was more than zero,
        total_used += used
      end
    end

    return [total_used, unit]
  end

  # this one's a bit tricker.  it's the total amount used of all items of this type purchased by this person.
  def amount_of_item_type_bought(item_type)
    total_used_from_purchases = 0.0
    unit = base_unit(item_type.measure_by)

    # parse the relevant items from the user's purchased items
    items_to_consider = items.where(:item_type => item_type)

    items_to_consider.each do |item|
      total_used_from_purchases += item.amount_used[:amount].to_f
    end

    return [total_used_from_purchases, unit]
  end

  # ok, put them together to get the share ratio.  like on bittorrent!
  def share_ratio(item_type)
    amount_bought = amount_of_item_type_bought(item_type)[0]
    amount_used = amount_of_item_type_used(item_type)[0]

    # check that our calculations make sense
    if amount_used > 0
      # if the amounts bought and used are positive, we have a nice fraction.
      ratio = amount_bought / amount_used
    elsif amount_used == 0 and amount_bought == 0
      ratio = 1
    else
      # if the amount used is zero, then the ratio is infinite
      ratio = 'infinity'
    end

    return ratio
  end

  # algorithm to determine someone's 'buyer score' for a particular item type.  A higher score means you're more likely to have to buy it.
  def buyer_score(item_type)
    ratio = share_ratio(item_type)
    share_delta = amount_of_item_type_used(item_type)[0] - amount_of_item_type_bought(item_type)[0]
    if ratio == 'infinity' or ratio > 1
      score = 0
    else
      score = share_delta ** 1.5 / (ratio + 0.01)
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < LoggedInController

  before_filter :find_person, :only => [ :show ]
  before_filter :owned_by_current_group, :only => [ :show ]

  def index
    if group_signed_in?
      @people = current_group.people
    else
      @people = Person.none
    end
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.create(person_params)
    @person.group = current_group

    if @person.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end
  
  def show
    @person = Person.find(params[:id])
    @item_types = current_group.item_types
  end

  def find_person
    @person = Person.find(params[:id])
  end

  def owned_by_current_group
    unless @person.group == current_group
      permissions_error_flash
    end
  end

  def person_params
    params.require(:person).permit(:name)
  end
end

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
  <% if @person.errors.any? %>
  <div id="errors">
    <h2><%= pluralize(@person.errors.count, "went") %> went wrong:</h2>
    <ul>
      <% @person.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div id="fields" class="large-8 medium-7">
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name %>

    <%= f.submit "add person", :class => "button" %>
    <%= link_to "cancel", people_path, :class => "button" %>
  </div>

<% end %>

app/views/people/_share_ratio_table.html.erb
<table>
  <thead>
    <tr>
      <td>Item</td>
      <td>Amount purchased</td>
      <td>Amount used</td>
      <td>Share ratio</td>
    </tr>
  </thead>
  <tbody>
    <% item_types.each do |item_type| %>
      <% purchased = person.amount_of_item_type_bought(item_type) %>
      <% used = person.amount_of_item_type_used(item_type) %>
      <% ratio = person.share_ratio(item_type) %>
    <tr>
      <td><%= link_to item_type.name, item_type_path(item_type) %></td>
      <td><%= number_with_precision(purchased[0], precision: 1) %> <%= purchased[1].pluralize(purchased[0]) %></td>
      <td><%= number_with_precision(used[0], precision: 1) %> <%= used[1].pluralize(used[0]) %></td>
      <td class=<%= share_ratio_class(ratio) %>><%= share_ratio_formatted(ratio) %></td>
    </tr>
    <% end %>
    <% if item_types.length == 0 %>
      <tr><td colspan=1>No share ratios</td></tr>
    <% end %>
  </tbody>
</table>

app/views/people/index.html.erb
<% content_for :page_heading do %>
<h1>People</h1>
<% end %>


<table>
  <thead>
    <tr>
      <td>Name</td>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
    <tr>
      <td><%= link_to person.name, person_path(person) %></td>
    </tr>
    <% end %>
    <% if @people.length == 0 %>
      <tr><td colspan=1>No people (yet!)</td></tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "add person",  new_person_path, :class => "button" %></p>

app/views/people/new.html.erb
<% content_for :page_heading do %>
<h1>Add new person</h1>
<% end %>

<%= render 'form' %>

app/views/people/show.html.erb
<% content_for :page_heading do %>
<h1><%= @person.name %></h1>
<% end %>


<h4>Sharing statistics</h4>
<%= render 'share_ratio_table', :item_types => @item_types, :person => @person %>


<h4>Usage history</h4>

<%= render 'uses/table', :uses => @person.uses, :person_page => true %>


<h4>Purchases</h4>

<%= render 'items/table', :items => @person.items, :person_page => true %>