config/routes.rb
Divvyup::Application.routes.draw do

  devise_for :groups
  resources :people
  
  resources :item_types
  
  resources :items do
    post :finish
  end
  
  resources :uses

  
  authenticated :group do
    root to: 'items#index', as: "authenticated_root"
  end

  unauthenticated do
    root to: 'welcome#index', as: "unauthenticated_root"
  end

end

app/controllers/item_types_controller.rb
  class ItemTypesController < LoggedInController

  before_filter :find_item_type, :only => [ :show ]
  before_filter :owned_by_current_group, :only => [ :show ]

  def index
    if group_signed_in?
      @item_types = current_group.item_types
    else
      @item_types = ItemType.none
    end
  end

  def new
    @item_type = ItemType.new
  end

  def create
    @item_type = ItemType.create(item_type_params)
    @item_type.group = current_group

    if @item_type.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def show
    @item_type = ItemType.find(params[:id])
    @people = current_group.people
  end

  def find_item_type
    @item_type = ItemType.find(params[:id])
  end

  def owned_by_current_group
    unless @item_type.group == current_group
      permissions_error_flash
    end
  end

  def item_type_params
    params.require(:item_type).permit(:name, :measure_by)
  end
end

app/helpers/item_types_helper.rb
module ItemTypesHelper
end

app/views/item_types/_form.html.erb
<%= form_for @item_type do |f| %>
  <% if @item_type.errors.any? %>
  <div id="errors">
    <h2><%= pluralize(@item_type.errors.count, "thing") %> went wrong:</h2>
    <ul>
      <% @item_type.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div id="fields" class="large-8 medium-7">
    <%= f.label :name, 'Name:' %>
    <%= f.text_field :name %>

    <%= f.label :measure_by, "Measure by..." %>
    <%= f.select :measure_by, options_for_select(%w[weight volume unit]) %>

    <%= f.submit "add this", :class => "button" %>
    <%= link_to "cancel", items_path, :class => "button" %>

  </div>

<% end %>

app/views/item_types/_share_ratio_table.html.erb
<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Amount purchased</td>
      <td>Amount used</td>
      <td>Share ratio</td>
    </tr>
  </thead>
  <tbody>
    <% people.each do |person| %>
      <% purchased = person.amount_of_item_type_bought(item_type) %>
      <% used = person.amount_of_item_type_used(item_type) %>
      <% ratio = person.share_ratio(item_type) %>
    <tr>
      <td><%= link_to person.name, person_path(person) %></td>
      <td><%= number_with_precision(purchased[0], precision: 1) %> <%= purchased[1].pluralize(purchased[0]) %></td>
      <td><%= number_with_precision(used[0], precision: 1) %> <%= used[1].pluralize(used[0]) %></td>
      <td class=<%= share_ratio_class(ratio) %>><%= share_ratio_formatted(ratio) %></td>
    </tr>
    <% end %>
    <% if @people.length == 0 %>
      <tr><td colspan=1>No share ratios</td></tr>
    <% end %>
  </tbody>
</table>

app/views/item_types/index.html.erb
<% content_for :page_heading do %>
<h1>Item statistics / admin</h1>
<% end %>


<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Measure by...</td>
    </tr>
  </thead>
  <tbody>
    <% @item_types.each do |item_type| %>
    <tr>
      <td><%= link_to item_type.name, item_type_path(item_type) %></td>
      <td><%= item_type.measure_by %></td>
    </tr>
    <% end %>
    <% if @item_types.length == 0 %>
      <tr><td colspan=2>No item types</td></tr>
    <% end %>
  </tbody>
</table>


<%= link_to "add item type",  new_item_type_path, :class => "button" %>

app/views/item_types/new.html.erb
<% content_for :page_heading do %>
<h1>Add new item type</h1>
<% end %>

<%= render 'form' %>

app/views/item_types/show.html.erb
<% content_for :page_heading do %>
<h1><%= @item_type.name %></h1>
<% end %>


<h4>Sharing statistics</h4>

<%# buyer = @item_type.next_buyer(current_group) %>
<% buyers = @item_type.next_buyers(current_group) %>

<h5><%= buyers.map{ |b| link_to(b.name, person_path(b)) }.to_sentence(last_word_connector: ', or ', two_words_connector: ' or ').html_safe %> should buy this next</h5>

<%= render 'share_ratio_table', :item_type => @item_type, :people => @people %>


<div id="charts" class="row">
  <div class="small-12 medium-6 columns">
    <h4>Usage (all time)</h4>
    <div id="usage-pie" class="small-10 small-offset-1 medium-10 medium-offset-0">
    </div>
  </div>
  <div class="small-12 medium-6 columns">
    <h4>Purchases (all time)</h4>
    <div id="purchase-pie" class="small-10 small-offset-1 medium-10 medium-offset-0">
    </div>
  </div>
</div>



<h4>Purchase history</h4>
<%= render 'items/table', :items => @item_type.items, :item_type_page => true %>


<script>
  var usage_data = <%=j @item_type.usage_stats.to_json.html_safe %>
  var purchase_data = <%=j @item_type.purchase_stats.to_json.html_safe %>
</script>