config/routes.rb
Divvyup::Application.routes.draw do

  devise_for :groups
  resources :people
  
  resources :item_types
  
  resources :items do
    post :finish
  end
  
  resources :uses

  
  authenticated :group do
    root to: 'items#index', as: "authenticated_root"
  end

  unauthenticated do
    root to: 'welcome#index', as: "unauthenticated_root"
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  include SharedMethods
  include ActionView::Helpers::NumberHelper

  # relations
  belongs_to :person
  belongs_to :item_type
  belongs_to :group
  has_many :uses

  # validations
  validates :person_id, presence: true
  validates :item_type_id, presence: true
  validates :group_id, presence: true
  validates :comment, length: { maximum: 100 }
  validate :groups_match?

  # scopes
  default_scope { order(finished: :asc, created_at: :desc) }
  scope :available, -> { where(finished: false) }
  scope :finished, -> { where(finished: true) }

  # before save hooks
  before_save :set_default_finished_flag
  def set_default_finished_flag
    self.finished ||= false
    true
  end

  # method to get how much has been used in total
  def amount_used
    total = 0.0
    uses.each do |use|
      total += use.amount_used
    end

    return {amount: number_with_precision(total, precision: 1), unit: base_unit(item_type.measure_by)}
  end

  # compile some statistics on usage (for the pie chart)
  def usage_stats
    # cycle through all people to see how much they used
    usage = []
    unit = base_unit(item_type.measure_by)
    Person.all.each do |person|
      used, unit = person.amount_of_item_used(self) # check how much has been used
      if used > 0 # if it was more than zero,
        used = number_with_precision(used, precision: 1)
        entry = {'person_name' => person.name, 'amount_used' => used, 'unit' => unit}
        usage.append(entry)
      end
    end

    # give a nice value if nothing was used yet
    if usage.length == 0
      usage = [{'person_name' => 'not used yet', 'amount_used' => 0, 'unit' => unit}]
    end

    return usage
  end

  def groups_match?
    if person.group.id != group.id
      errors.add(:person, "must be in your group")
    end
    if item_type.group.id != group.id
      errors.add(:item_type, "must belong to your group")
    end
  end

end

app/models/item_type.rb
class ItemType < ActiveRecord::Base
  include SharedMethods
  include ActionView::Helpers::NumberHelper

  # relations
  belongs_to :group
  has_many :items

  # validations
  validates :group_id, presence: true
  validates :measure_by, inclusion: %w(volume weight unit)
  validates :name, length: { minimum: 1 }

  # scopes
  default_scope { order(name: :asc) }

  # compile some statistics on usage (for the pie charts)
  def usage_stats
    # cycle through all people to see how much they used
    usage = []
    Person.all.each do |person|
      used, unit = person.amount_of_item_type_used(self)
      if used > 0
        used = number_with_precision(used, precision: 1)
        entry = {'person_name' => person.name, 'amount_used' => used, 'unit' => unit}
        usage.append(entry)
      end
    end

    # give a nice value if nothing was used yet
    if usage.length == 0
      usage = [{'person_name' => 'not used yet', 'amount_used' => 0, 'unit' => measure_by}]
    end

    return usage
  end

  # get the stats on purchase history too
  def purchase_stats
    # cycle through all people to see how much they bought
    supplied = []
    Person.all.each do |person|
      supply, unit = person.amount_of_item_type_bought(self)
      if supply > 0
        supply = number_with_precision(supply, precision: 1)
        entry = {'person_name' => person.name, 'amount_purchased' => supply, 'unit' => unit}
        supplied.append(entry)
      end
    end

    return supplied
  end

  # and find out who should buy the next one!
  def next_buyers(group)
    users = {}
    Person.where(group: group).each do |person|
      users[person.id] = person.buyer_score(self)
    end

    # buyer = Person.find(users.sort_by{ |id, score| score }.last[0])

    potential_buyer = users.sort_by{ |id, score| score }.last
    buyer_ids = []
    for user in users
      if user[1] == potential_buyer[1]
        buyer_ids.append(user[0])
      end
    end
    buyers = Person.find(buyer_ids)

  end
end

app/controllers/items_controller.rb
class ItemsController < LoggedInController

  before_filter :find_item, :only => [ :show, :finish ]
  before_filter :owned_by_current_group, :only => [ :show, :finish ]

  def index
    if group_signed_in?
      @items = current_group.items
    else
      @items = Item.none
    end
  end

  def new
    @item = Item.new
    new_or_create_init
  end

  def create
    @item = Item.new(item_params)
    @item.group = current_group
    new_or_create_init

    if @item.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def show
  end

  def finish
    @item.finished = true
    @item.finished_at = DateTime.now

    unless @item.save
      flash[:alert] = "item could not be finished"
    end

    redirect_to action: 'index'
  end

  def find_item
    @item = Item.find(params[:item_id] || params[:id])  # the second part shouldn't be evaluated if the first returns true :)
  end

  def owned_by_current_group
    unless @item.group == current_group
      permissions_error_flash
    end
  end

  def new_or_create_init
    @people = current_group.people
    @item_types = current_group.item_types
  end

  def item_params
    params.require(:item).permit(:person_id, :item_type_id, :id, :comment)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <% if @item.errors.any? %>
  <div id="errors">
    <h2><%= pluralize(@item.errors.count, "thing") %> went wrong:</h2>
    <ul>
      <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div id="fields" class="large-8 medium-7">
    <%= f.label :item_type_id, "What is it?" %>
    <%= f.collection_select :item_type_id, @item_types, :id, :name %>

    <%= f.label :person_id, "Who bought it?" %>
    <%= f.collection_select :person_id, @people, :id, :name %>

    <%= f.label :comment, "Comments (optional)" %>
    <%= f.text_field :comment %>

    <%= f.submit "add this", :class => "button" %>
    <%= link_to "cancel", items_path, :class => "button" %>
  </div>

<% end %>

app/views/items/_table.html.erb
<% person_page ||= false %>

<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Date added</td>
      <% unless person_page %>
      <td>Purchased by</td>
      <% end %>
      <td>Units</td>
      <td>Amount used</td>
      <td>Comments</td>
      <td colspan=2></td>
    </tr>
  </thead>
  <tbody>
    <% items.each do |item| %>
    <tr>
      <td><%= link_to item.item_type.name, item_path(item) %></td>
      <td><%= item.created_at.to_formatted_s(:short_date) %></td>
      <% unless person_page %>
      <td><%= link_to item.person.name, person_path(item.person) %></td>
      <% end %>
      <td><%= item.item_type.measure_by %></td>
        <% amount_used = item.amount_used %>
      <td><%= amount_used[:amount] %> <%= amount_used[:unit].pluralize(amount_used[:amount]) %></td>
      <td><%= item.comment || "" %></td> <%# this leaves it blank if it's nil %>
        <% if item.finished %>
      <td colspan=2>finished on <%= item.finished_at.to_formatted_s(:short_date) %></td>
        <% else %>
      <td><%= link_to "use", new_use_path({:use => {:item_id => item.id}}) %></td>
      <td>
        <a href data-reveal-id="confirm-finish-<%= item.id %>">finish</a>
        <div id="confirm-finish-<%= item.id %>" class="reveal-modal medium" data-reveal>
          <h3>Finish this item?</h3>
          <p>This will make the item unavailable for use.</p>
          <div class="row">
            <%= link_to "finish it", item_finish_path(item), method: :post, class: "button large-4 medium-5 columns" %>
            <a class="button large-5 large-offset-1 medium-6 columns" href>oops, don't</a>
          </div>
          <a class="close-reveal-modal">&#215;</a>
        </div>
      </td>
        <% end %>
    </tr>
    <% end %>
    <% if items.length == 0 %>
      <tr><td colspan=7>No items</td></tr>
    <% end %>
  </tbody>
</table>

app/views/items/index.html.erb
<% content_for :page_heading do %>
<h1>Items</h1>
<% end %>


<%= render 'table', :items => @items %>

<%= link_to "add item", new_item_path, :class => "button" %>

app/views/items/new.html.erb
<% content_for :page_heading do %>
<h1>Add new item</h1>
<% end %>

<%= render 'form' %>

app/views/items/show.html.erb
<% content_for :page_heading do %>
<h1><%= link_to @item.item_type.name, item_type_path(@item.item_type) %></h1>
<% end %>



<h5><em><%= @item.comment %></em></h5>

<p>Purchased on <strong><%= @item.created_at.to_date.to_formatted_s(:long_ordinal) %></strong> by <strong><%= link_to @item.person.name, person_path(@item.person) %></strong></p>

<% amount_used = @item.amount_used %>
<% if @item.finished %>
  <p>Finished on <strong><%= @item.finished_at.to_date.to_formatted_s(:long_ordinal) %></strong></p>
  <p><strong><%= amount_used[:amount] %> <%= amount_used[:unit].pluralize(amount_used[:amount]) %></strong> used</p>
<% else %>
  <p><strong><%= amount_used[:amount] %> <%= amount_used[:unit].pluralize(amount_used[:amount]) %></strong> used so far</p>
<% end %>



<div id="charts" class="row">
  <div class="small-12 medium-6 columns">
    <h4>Usage by person</h4>
    <div id="usage-pie" class="small-10 small-offset-1 medium-10 medium-offset-0">
    </div>
  </div>
</div>


<h4>Usage history</h4>

<%= render 'uses/table', :uses => @item.uses, :item_page => true %>


<script>
  var usage_data = <%=j @item.usage_stats.to_json.html_safe %>
</script>