config/routes.rb
Divvyup::Application.routes.draw do

  devise_for :groups
  resources :people
  
  resources :item_types
  
  resources :items do
    post :finish
  end
  
  resources :uses

  
  authenticated :group do
    root to: 'items#index', as: "authenticated_root"
  end

  unauthenticated do
    root to: 'welcome#index', as: "unauthenticated_root"
  end

end

app/views/layouts/_top_bar.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">divvyup</a></h1>
    </li>

    <%# <li class="toggle-topbar menu-icon"> %>
    <li class="toggle-topbar">
      <a href>menu</a>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <% if group_signed_in? %>
        <li><%= link_to "items", items_path %></li>
        <li><%= link_to "item stats", item_types_path %></li>
        <li><%= link_to "people", people_path %></li>
        <li><%= link_to "usage history", uses_path %></li>
        <li class="has-dropdown">
          <a href="#"><%= current_group.group_name %></a>
          <ul class="dropdown">
            <li><%= link_to "edit account", edit_group_registration_path %></li>
            <li><%= link_to "sign out", destroy_group_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><a href="<%= new_group_session_path %>">sign in</a></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>divvyup<%= content_for?(:title) ? " | " + yield(:title) : "" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>

    <%= render 'layouts/top_bar' %>

    <div id="spacer" class="row show-for-medium-up top-spacer"></div>

    <div class="row">
      <div id="content" class="large-10 large-offset-2 medium-11 medium-offset-1 columns">
        <%= yield :page_heading %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div> <!-- /content -->
    </div> <!-- /main row -->
    <%= javascript_include_tag "application" %>
    <%= javascript_pluggable_tag %>
  </body>
</html>